ammolist-master/config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :ammolist_taxon_calibers
  resources :guest_user_ips, only: [:index, :destroy] do
    collection do
      post 'block_guest'
    end
  end
  
  mount Spree::Core::Engine, :at => '/'

  get 'taxons/all_products', to: 'spree/taxons#all_products', as: :taxon_all_products
  get 'taxons/taxons_products', to: 'spree/taxons#taxons_products', as: :taxons_products
  get 'taxons/taxon_product_info', to: 'spree/taxons#taxon_product_info', as: :taxon_product_info
  get 'taxons/taxon_update_point', to: 'spree/taxons#taxon_update_point', as: :taxon_update_point
  get 'taxons/taxon_update_user_ammolist', to: 'spree/taxons#taxon_update_user_ammolist', as: :taxon_update_user_ammolist
  get 'taxons/taxon_subscribe_user_ammolist', to: 'spree/taxons#taxon_subscribe_user_ammolist', as: :taxon_subscribe_user_ammolist
  get 'taxons/taxon_get_user_ammolist', to: 'spree/taxons#taxon_get_user_ammolist', as: :taxon_get_user_ammolist
  get 'subscriptions/subscribe', to: 'spree/subscriptions#subscribe', as: :email_subscribe

  comfy_route :cms_admin, :path => ComfortableMexicanSofa.config.admin_route_path

  scope :module => :comfy, :as => :comfy do
    scope :module => :admin do
      namespace :cms, :as => :admin_cms, :path => 'admin', :except => :show do
        scope :path => ComfortableMexicanSofa.config.cms_route_path do
          resources :sites do
            resources :shared_media
          end
        end
      end
    end

    scope :module => :cms do
      scope :path => ComfortableMexicanSofa.config.cms_route_path do
        get 'feed' => 'content#feed', :as => 'feed'
      end
    end
  end

  comfy_route :cms, :path => ComfortableMexicanSofa.config.cms_route_path, :sitemap => false
  
end

Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :shipping_constraints
    resources :constraint_types
    resources :ammunitions
    
    resources :products do
      resources :questions
    end
    
    resources :questions, only: [] do
      collection do
        get :pending
      end
    end
    
  end
  
  resources :questions, only: [:create]
  
  post '/checkout/update_delivery', :to => 'checkout#update_delivery', :as => :checkout_update_delivery
  post '/checkout/update_shipment_upgrade', :to => 'checkout#update_shipment_upgrade', :as => :checkout_update_shipment_upgrade
  post '/checkout/summary', :to => 'checkout#summary', :as => :checkout_summary
  get '/customs/bloked_user', :to => 'customs#bloked_user', :as => :customs_bloked_user
  get '/customs/blocked_guest', :to => 'customs#blocked_guest', :as => :customs_blocked_guest
  post '/admin/orders/update_shipment_upgrade', :to => 'admin/orders#update_shipment_upgrade', :as => :checkout_update_shipment_upgrade_admin
end

ammolist-master/app/models/spree/address.rb
module Spree
  class Address < Spree::Base
    require 'twitter_cldr'

    belongs_to :country, class_name: "Spree::Country"
    belongs_to :state, class_name: "Spree::State"

    has_many :shipments, inverse_of: :address

    validates :firstname, :lastname, :address1, :city, :country, presence: true, if: :require_data?
    validates :zipcode, presence: true, if: :require_zipcode? && :require_data?
    validates :phone, presence: true, if: :require_phone? && :require_data?

    validate :state_validate, :postal_code_validate, if: :require_data?

    alias_attribute :first_name, :firstname
    alias_attribute :last_name, :lastname

    attr_accessor :require_data 

    def self.build_default
      country = Spree::Country.find(Spree::Config[:default_country_id]) rescue Spree::Country.first
      new(country: country, require_data: true)
    end

    def self.build_default_require_data(is_require_data)
      country = Spree::Country.find(Spree::Config[:default_country_id]) rescue Spree::Country.first
      new(country: country, require_data: is_require_data)
    end

    def self.default(user = nil, kind = "bill")
      if user && user_address = user.send(:"#{kind}_address")
        user_address.clone
      else
        build_default
      end
    end

    # Can modify an address if it's not been used in an order (but checkouts controller has finer control)
    # def editable?
    #   new_record? || (shipments.empty? && checkouts.empty?)
    # end

    def full_name
      "#{firstname} #{lastname}".strip
    end

    def state_text
      state.try(:abbr) || state.try(:name) || state_name
    end

    def same_as?(other)
      return false if other.nil?
      attributes.except('id', 'updated_at', 'created_at') == other.attributes.except('id', 'updated_at', 'created_at')
    end

    alias same_as same_as?

    def to_s
      "#{full_name}: #{address1}"
    end

    def clone
      self.class.new(self.attributes.except('id', 'updated_at', 'created_at'))
    end

    def ==(other_address)
      self_attrs = self.attributes
      other_attrs = other_address.respond_to?(:attributes) ? other_address.attributes : {}

      [self_attrs, other_attrs].each { |attrs| attrs.except!('id', 'created_at', 'updated_at', 'order_id') }

      self_attrs == other_attrs
    end

    def empty?
      attributes.except('id', 'created_at', 'updated_at', 'order_id', 'country_id').all? { |_, v| v.nil? }
    end

    # Generates an ActiveMerchant compatible address hash
    def active_merchant_hash
      {
        name: full_name,
        address1: address1,
        address2: address2,
        city: city,
        state: state_text,
        zip: zipcode,
        country: country.try(:iso),
        phone: phone
      }
    end

    def require_phone?
      true
    end

    def require_zipcode?
      true
    end

    def require_data?
      @require_data
    end

    private
      def state_validate
        # Skip state validation without country (also required)
        # or when disabled by preference
        return if country.blank? || !Spree::Config[:address_requires_state]
        return unless country.states_required

        # ensure associated state belongs to country
        if state.present?
          if state.country == country
            self.state_name = nil #not required as we have a valid state and country combo
          else
            if state_name.present?
              self.state = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure state_name belongs to country without states, or that it matches a predefined state name/abbr
        if state_name.present?
          if country.states.present?
            states = country.states.find_all_by_name_or_abbr(state_name)

            if states.size == 1
              self.state = states.first
              self.state_name = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure at least one state field is populated
        errors.add :state, :blank if state.blank? && state_name.blank?
      end

      def postal_code_validate
        return if country.blank? || country.iso.blank? || !require_zipcode?
        return if !TwitterCldr::Shared::PostalCodes.territories.include?(country.iso.downcase.to_sym)

        postal_code = TwitterCldr::Shared::PostalCodes.for_territory(country.iso)
        errors.add(:zipcode, :invalid) if !postal_code.valid?(zipcode.to_s)
      end
  end
end

ammolist-master/app/models/spree/ammunition.rb
class Spree::Ammunition < ActiveRecord::Base
  #default_scope -> { order("position ASC") }

  validates_presence_of :title
  validates_presence_of :body

  has_many :product, class_name: 'Spree::Product'

end

ammolist-master/app/models/spree/answer.rb
class Spree::Answer < ActiveRecord::Base
  belongs_to :question

  validates :content, presence: true

  #after_create :send_email, if: ->() { SpreeProductsQa.send_email? }
  
  after_create :send_email

  def send_email
        #QaMailerWorker.perform_async(self.question.id) if self.question.present?
        QaAnswerMailer.answer_email(self.question).deliver if self.question.present?
  end
end

ammolist-master/app/models/spree/constraint_type.rb
module Spree
  class ConstraintType < Spree::Base
    has_many :shipping_constraints, inverse_of: :shipping_method
    has_many :shipping_methods, through: :shipping_constraints
    accepts_nested_attributes_for :shipping_constraints
    attr_accessor :total
  end
end

ammolist-master/app/models/spree/order_updater.rb
module Spree
  class OrderUpdater
    attr_reader :order
    delegate :payments, :line_items, :adjustments, :all_adjustments, :shipments, :update_hooks, :quantity, to: :order

    def initialize(order)
      @order = order
    end

    # This is a multi-purpose method for processing logic related to changes in the Order.
    # It is meant to be called from various observers so that the Order is aware of changes
    # that affect totals and other values stored in the Order.
    #
    # This method should never do anything to the Order that results in a save call on the
    # object with callbacks (otherwise you will end up in an infinite recursion as the
    # associations try to save and then in turn try to call +update!+ again.)
    def update
      update_totals
      if order.completed?
        update_payment_state
        update_shipments
        update_shipment_state
      end
      run_hooks
      persist_totals
    end

    def run_hooks
      update_hooks.each { |hook| order.send hook }
    end

    def recalculate_adjustments
      all_adjustments.includes(:adjustable).map(&:adjustable).uniq.each { |adjustable| Spree::ItemAdjustments.new(adjustable).update }
    end

    # Updates the following Order total values:
    #
    # +payment_total+      The total value of all finalized Payments (NOTE: non-finalized Payments are excluded)
    # +item_total+         The total value of all LineItems
    # +adjustment_total+   The total value of all adjustments (promotions, credits, etc.)
    # +promo_total+        The total value of all promotion adjustments
    # +total+              The so-called "order total."  This is equivalent to +item_total+ plus +adjustment_total+.
    def update_totals
      update_payment_total
      update_item_total
      update_shipment_total
      update_adjustment_total
    end


    # give each of the shipments a chance to update themselves
    def update_shipments
      shipments.each do |shipment|
        next unless shipment.persisted?
        shipment.update!(order)
        shipment.refresh_rates
        shipment.update_amounts
      end
    end

    def update_payment_total
      order.payment_total = payments.completed.sum(:amount)
    end

    def update_shipment_total
      order.shipment_total = shipments.to_a.sum(&:cost_with_upgrade)
      update_order_total
    end

    def update_order_total
      order.total = order.item_total + order.shipment_total + order.adjustment_total
    end

    def update_adjustment_total
      recalculate_adjustments
      order.adjustment_total = line_items.sum(:adjustment_total) +
                               shipments.sum(:adjustment_total)  +
                               adjustments.eligible.sum(:amount)
      order.included_tax_total = line_items.sum(:included_tax_total) + shipments.sum(:included_tax_total)
      order.additional_tax_total = line_items.sum(:additional_tax_total) + shipments.sum(:additional_tax_total)

      order.promo_total = line_items.sum(:promo_total) +
                          shipments.sum(:promo_total) +
                          adjustments.promotion.eligible.sum(:amount)

      update_order_total
    end

    def update_item_count
      order.item_count = quantity
    end

    def update_item_total
      order.item_total = line_items.sum('price * quantity')
      update_order_total
    end

    def persist_totals
      order.update_columns(
        payment_state: order.payment_state,
        shipment_state: order.shipment_state,
        item_total: order.item_total,
        item_count: order.item_count,
        adjustment_total: order.adjustment_total,
        included_tax_total: order.included_tax_total,
        additional_tax_total: order.additional_tax_total,
        payment_total: order.payment_total,
        shipment_total: order.shipment_total,
        promo_total: order.promo_total,
        total: order.total,
        updated_at: Time.now,
      )
    end

    # Updates the +shipment_state+ attribute according to the following logic:
    #
    # shipped   when all Shipments are in the "shipped" state
    # partial   when at least one Shipment has a state of "shipped" and there is another Shipment with a state other than "shipped"
    #           or there are InventoryUnits associated with the order that have a state of "sold" but are not associated with a Shipment.
    # ready     when all Shipments are in the "ready" state
    # backorder when there is backordered inventory associated with an order
    # pending   when all Shipments are in the "pending" state
    #
    # The +shipment_state+ value helps with reporting, etc. since it provides a quick and easy way to locate Orders needing attention.
    def update_shipment_state
      if order.backordered?
        order.shipment_state = 'backorder'
      else
        # get all the shipment states for this order
        shipment_states = shipments.states
        if shipment_states.size > 1
          # multiple shiment states means it's most likely partially shipped
          order.shipment_state = 'partial'
        else
          # will return nil if no shipments are found
          order.shipment_state = shipment_states.first
          # TODO inventory unit states?
          # if order.shipment_state && order.inventory_units.where(:shipment_id => nil).exists?
          #   shipments exist but there are unassigned inventory units
          #   order.shipment_state = 'partial'
          # end
        end
      end

      order.state_changed('shipment')
      order.shipment_state
    end

    # Updates the +payment_state+ attribute according to the following logic:
    #
    # paid          when +payment_total+ is equal to +total+
    # balance_due   when +payment_total+ is less than +total+
    # credit_owed   when +payment_total+ is greater than +total+
    # failed        when most recent payment is in the failed state
    #
    # The +payment_state+ value helps with reporting, etc. since it provides a quick and easy way to locate Orders needing attention.
    def update_payment_state
      last_state = order.payment_state
      if payments.present? && payments.valid.size == 0
        order.payment_state = 'failed'
      elsif !payments.present? && order.state == 'canceled'
        order.payment_state = 'void'
      elsif order.state == 'canceled' && order.payment_total == 0 && payments.completed.size > 0
        order.payment_state = 'void'
      else
        order.payment_state = 'balance_due' if order.outstanding_balance > 0
        order.payment_state = 'credit_owed' if order.outstanding_balance < 0
        order.payment_state = 'paid' if !order.outstanding_balance?
      end
      order.state_changed('payment') if last_state != order.payment_state
      order.payment_state
    end

    private
      def round_money(n)
        (n * 100).round / 100.0
      end
  end
end

ammolist-master/app/models/spree/product_decorator.rb
Spree::Product.class_eval do
    belongs_to :ammunition, class_name: 'Spree::Ammunition'
    has_many :questions
end

ammolist-master/app/models/spree/product_property.rb
module Spree
  class ProductProperty < Spree::Base
    belongs_to :product, touch: true, class_name: 'Spree::Product', inverse_of: :product_properties
    belongs_to :property, class_name: 'Spree::Property', inverse_of: :product_properties

    validates :property, presence: true

    validates_with Spree::Validations::DbMaximumLengthValidator, field: :value

    default_scope -> { order("#{self.table_name}.position") }

    # virtual attributes for use with AJAX completion stuff
    def property_name
      property.name if property
    end

    def property_name=(name)
      unless name.blank?
        unless property = Property.find_by(name: name)
          property = Property.create(name: name, presentation: name)
        end
        self.property = property
      end
    end
  end
end

ammolist-master/app/models/spree/question.rb
class Spree::Question < ActiveRecord::Base
  belongs_to :product
  has_one :answer, dependent: :destroy
  belongs_to :user, class_name: 'Spree::User'
  accepts_nested_attributes_for :answer

  default_scope ->{ order("spree_questions.created_at DESC") }
  scope :visible, ->{ where(is_visible: true) }
  scope :answered, ->{ joins(:answer) }
  scope :not_answered, ->{ where.not(id: self.answered.pluck(:id)) }
  
  mount_uploader :image, ImageUploader


  validates :content, presence: true

  def answer_for_form
    self.answer.present? ? self.answer : self.build_answer
  end
end

ammolist-master/app/models/spree/shipment_upgrade.rb
module Spree
  class ShipmentUpgrade < Spree::Base
    belongs_to :shipment, class_name: 'Spree::Shipment'
    belongs_to :shipping_method_upgrade, class_name: 'Spree::ShippingMethodUpgrade', inverse_of: :shipment_upgrades
    
    delegate :currency, to: :shipment

    before_save :calculated_cost

    def calculated_cost
      calculated_cost = shipping_method_upgrade.calculator(shipment)
      write_attribute(:cost, calculated_cost)
    end

    def display_cost
      Spree::Money.new(cost, currency: currency)
    end

  end
end

ammolist-master/app/models/spree/shipping_constraint.rb
module Spree
  class ShippingConstraint < Spree::Base
    belongs_to :constraint_type, class_name: 'Spree::ConstraintType'
    belongs_to :shipping_method, class_name: 'Spree::ShippingMethod'
  end
end

ammolist-master/app/models/spree/user_subscription.rb
module Spree
  class UserSubscription < Spree::Base
  end
end

ammolist-master/app/views/spree/checkout/_delivery.html.erb
<fieldset id='shipping_method' data-hook>
  <legend align="center"><%= Spree.t(:delivery) %></legend>
  <div class="inner" data-hook="shipping_method_inner">
    <div id="methods">
      <% is_an_option = false %>
      <%= form.fields_for :shipments do |ship_form| %>

        <div class="shipment">
          <h3 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:package_from) %>
            <strong class="stock-location-name" data-hook="stock-location-name"><%= ship_form.object.stock_location.name %></strong>
          </h3>

          <table class="stock-contents" data-hook="stock-contents">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% ship_form.object.manifest.each do |item| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(item.variant) %></td>
                  <td class="item-name"><%= item.variant.name %></td>
                  <td class="item-qty"><%= item.quantity %></td>
                  <td class="item-price"><%= display_price(item.variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <h5 class="stock-shipping-method-title"><%= Spree.t(:shipping_method) %></h5>
          <ul class="field radios shipping-methods">
            <% is_represented = true %>
            <% ship_form.object.shipping_rates.each do |rate| %>
              <li class="shipping-method">
                <% disallow_message = ship_form.object.disallow_message(rate) %>
                <label>
                  <%= ship_form.radio_button :selected_shipping_rate_id, rate.id, :class => is_represented ? "required": "", :title => is_represented ? "Please choose one or update your cart": "", :disabled => disallow_message.empty? ? false : true, :data => { "shipment-id" => ship_form.object.id, "shipment_form_id" => ship_form.index}  %>
                  <% is_represented = false %>
                  <span class="rate-name"><%= rate.name %></span>
                  <span class="rate-cost"><%= rate.display_cost %></span>
                  <% if disallow_message.empty? %>
                    <% is_an_option = true %>
                  <% else %>
                    <span class="rate-disallow" style="color: red;"><%= "Can't be selected: "+disallow_message %></span>
                  <% end %>
                </label>
              </li>
            <% end %>
            <br/>
            <label style="display: none;" class="error" for="order[shipments_attributes][<%=ship_form.index%>][selected_shipping_rate_id]"></label>

          </ul>
          <div id="shipping_upgrade_<%=ship_form.index%>">
            <%= render :partial => 'spree/checkout/shipping_upgrade_form', :locals => { :ship_id => ship_form.object.id, :ship_form_id => ship_form.index, :ship_upgrade_opts => ship_form.object.shipment_upgrades_options } %>
          </div>
        </div>
        <br/>
      <% end %>

      <% if @differentiator.try(:missing?) %>
        <div class="shipment unshippable">
          <h3 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:unshippable_items) %>
          </h3>
          <table class="stock-contents" data-hook="stock-missing">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% @differentiator.missing.each do |variant, quantity| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(variant) %></td>
                  <td class="item-name"><%= variant.name %></td>
                  <td class="item-qty"><%= quantity %></td>
                  <td class="item-price"><%= display_price(variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>

    </div>
    <% if Spree::Config[:shipping_instructions] %>
      <p id="minstrs" data-hook>
        <%= form.label :special_instructions, Spree.t(:shipping_instructions) %><br />
        <%= form.text_area :special_instructions, :cols => 40, :rows => 7 %>
      </p>
    <% end %>
  </div>
</fieldset>

<br />

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), :class => 'continue button primary', :disabled => is_an_option ? false : true %>
  <%= is_an_option ? "" : "<label class='error' >Can't be submited: you should choose one shipment method above or modify your cart</label>".html_safe %>
</div>

ammolist-master/app/views/spree/checkout/_form_wrapper.html.erb
<div data-hook="checkout_progress"><%= checkout_progress %></div>
<div id="checkout_<%=state%>_wrapper" class="columns <%= if state != 'confirm' then 'alpha nine' else 'alpha omega twelve' end %>" data-hook="checkout_form_wrapper">

  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => order } %>

  <%= form_for order, :url => update_checkout_path(state), :remote => (state != 'confirm' && state != 'payment'), :html => { :id => "checkout_form_#{state}" } do |form| %>
    <% unless order.email? %>
      <p id="customer-email" class="field" style='clear: both'>
        <%= form.label :email %><br />
        <%= form.text_field :email %>
      </p>
    <% end %>

    <%= render state, :form => form %>
  <% end %>
</div>

<div id="checkout-information" class="columns omega three">
  <% if state != 'confirm' %>
    <div id="checkout-summary" data-hook="checkout_summary_box">
      <%= render :partial => 'summary', :locals => { :order => order } %>
    </div>
    <div id="contact-info">
      <% properties.each do |prop| %>
        <%= raw(prop.content_cache) %>
      <% end %>
    </div>
  <% end %>
  
</div>

ammolist-master/app/views/spree/checkout/_payment.html.erb
<fieldset id="payment" data-hook>
  <legend align="center"><%= Spree.t(:payment_information) %></legend>
  <div data-hook="checkout_payment_step">

    <% if @payment_sources.present? %>
      <div class="card_options">
        <%= radio_button_tag 'use_existing_card', 'yes', true %>
        <label for="use_existing_card_yes">Use an existing card on file</label>
        <br/>
        <%= radio_button_tag 'use_existing_card', 'no' %>
        <label for="use_existing_card_no">Use a new card / payment method</label>
      </div>

      <div id="existing_cards">
        <p class="field" data-hook="existing_cards">
          <table class="existing-credit-card-list">
            <tbody>
              <% @payment_sources.each do |card| %>
                <tr id="<%= dom_id(card,'spree')%>" class="<%= cycle('even', 'odd') %>">
                  <td><%= card.name %></td>
                  <td><%= card.display_number %></td>
                  <td><%= card.month %></td>
                  <td><%= card.year %></td>
                  <td>
                    <%= radio_button_tag "order[existing_card]", card.id, (card == @payment_sources.first), { class: "existing-cc-radio" }  %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </p>
      </div>
    <% end %>

    <div id="payment-method-fields" data-hook>
      <% @order.available_payment_methods.each do |method| %>
      <p>
        <label>
          <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.available_payment_methods.first %>
          <%= Spree.t(method.name, :scope => :payment_methods, :default => method.name) %>
        </label>
      </p>
      <% end %>
    </div>

    <ul id="payment-methods" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>" data-hook>
          <fieldset>
            <%= render :partial => "spree/checkout/payment/#{method.method_type}", :locals => { :payment_method => method } %>
          </fieldset>
        </li>
      <% end %>
    </ul>
    <br style="clear:both;" />
    <p class='field' data-hook='coupon_code'>
      <%= form.label :coupon_code %><br />
      <%= form.text_field :coupon_code %>
    </p>
  </div>
</fieldset>

<br class="space" />

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), :class => 'continue button primary' %>
</div>

ammolist-master/app/views/spree/checkout/_shipping_upgrade_form.html.erb
<h5 class="stock-shipping-upgrade-title"><%= t(:shipping_upgrade) %></h5>
<ul class="field checkbox shipping-methods">
  <% ship_upgrade_opts.each do |upgrade| %>
  <li class="shipping-upgrade">
    <label>
      <%= check_box_tag('order[shipments_attributes]['+ship_form_id.to_s+'][selected_shipment_upgrade_id][]', upgrade.id, upgrade.selected, :data => { "shipment-id" => ship_id }) %>
      <span class="upgrade-name"><%= upgrade.shipping_method_upgrade.shipping_upgrade.name %></span>              
      <span class="upgrade-cost"><%= upgrade.display_cost %></span>
    </label>
    <br/>
  </li>
  <% end %>
</ul>

ammolist-master/app/views/spree/checkout/_summary.html.erb
<div class="modal-summary modal"></div>
<h3 class="order-h3"><%= Spree.t(:order) %> #<%= order.number %></h3>
<h3><%= Spree.t(:order_summary) %></h3>

<table data-hook="order_summary">
  <tbody>
    <tr data-hook="item_total">
      <td><strong><%= Spree.t(:item_total) %>:</strong></td>
      <td><strong><%= order.display_item_total.to_html %></strong></td>
    </tr>

    <% if order.line_item_adjustments.nonzero.exists? %>
      <tbody data-hook="order_details_promotion_adjustments">
        <% order.line_item_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
          <tr class="total">
            <td><%= label %></td>
            <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>

    <tbody data-hook="order_details_tax_adjustments">
      <% order.all_adjustments.nonzero.tax.eligible.group_by(&:label).each do |label, adjustments| %>
        <tr class="total">
          <td><%= label %></td>
          <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
        </tr>
      <% end %>
    </tbody>

    <% if order.shipments.any? %>
      <% order.shipments.each do |shipment| %>
        <tr id="shipment_cost">
          <td><%= Spree.t(:shipping) %>: <%= shipment.shipping_method.name %></td>
          <td><%= shipment.display_discounted_cost %></td>
        </tr>
        <% shipment.selected_shipment_upgrade.each do |upgrade| %>
          <tr id="shipment_upgrade_cost">
            <td><%= upgrade.shipping_method_upgrade.shipping_upgrade.name %></td>
            <td><%= upgrade.display_cost %></td>
          </tr>
        <% end %>
      <% end %>

      <% if order.shipment_adjustments.nonzero.exists? %>
        <tbody data-hook="order_details_shipment_promotion_adjustments">
          <% order.shipment_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
            <tr class="total">
              <td><%= label %>:</td>
              <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    <% end %>

    <% if order.adjustments.nonzero.eligible.exists? %>
      <tbody id="summary-order-charges" data-hook>
        <% order.adjustments.nonzero.eligible.each do |adjustment| %>
        <% next if (adjustment.source_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
          <tr class="total">
            <td><%= adjustment.label %>:</td>
            <td><%= adjustment.display_amount.to_html %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>

    <tr data-hook="order_total">
      <td><strong><%= Spree.t(:order_total) %>:</strong></td>
      <td><strong><span id='summary-order-total'><%= order.display_total.to_html %></span></strong></td>
    </tr>
  </tbody>
</table>