ammolist-master/config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :ammolist_taxon_calibers
  resources :guest_user_ips, only: [:index, :destroy] do
    collection do
      post 'block_guest'
    end
  end
  
  mount Spree::Core::Engine, :at => '/'

  get 'taxons/all_products', to: 'spree/taxons#all_products', as: :taxon_all_products
  get 'taxons/taxons_products', to: 'spree/taxons#taxons_products', as: :taxons_products
  get 'taxons/taxon_product_info', to: 'spree/taxons#taxon_product_info', as: :taxon_product_info
  get 'taxons/taxon_update_point', to: 'spree/taxons#taxon_update_point', as: :taxon_update_point
  get 'taxons/taxon_update_user_ammolist', to: 'spree/taxons#taxon_update_user_ammolist', as: :taxon_update_user_ammolist
  get 'taxons/taxon_subscribe_user_ammolist', to: 'spree/taxons#taxon_subscribe_user_ammolist', as: :taxon_subscribe_user_ammolist
  get 'taxons/taxon_get_user_ammolist', to: 'spree/taxons#taxon_get_user_ammolist', as: :taxon_get_user_ammolist
  get 'subscriptions/subscribe', to: 'spree/subscriptions#subscribe', as: :email_subscribe

  comfy_route :cms_admin, :path => ComfortableMexicanSofa.config.admin_route_path

  scope :module => :comfy, :as => :comfy do
    scope :module => :admin do
      namespace :cms, :as => :admin_cms, :path => 'admin', :except => :show do
        scope :path => ComfortableMexicanSofa.config.cms_route_path do
          resources :sites do
            resources :shared_media
          end
        end
      end
    end

    scope :module => :cms do
      scope :path => ComfortableMexicanSofa.config.cms_route_path do
        get 'feed' => 'content#feed', :as => 'feed'
      end
    end
  end

  comfy_route :cms, :path => ComfortableMexicanSofa.config.cms_route_path, :sitemap => false
  
end

Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :shipping_constraints
    resources :constraint_types
    resources :ammunitions
    
    resources :products do
      resources :questions
    end
    
    resources :questions, only: [] do
      collection do
        get :pending
      end
    end
    
  end
  
  resources :questions, only: [:create]
  
  post '/checkout/update_delivery', :to => 'checkout#update_delivery', :as => :checkout_update_delivery
  post '/checkout/update_shipment_upgrade', :to => 'checkout#update_shipment_upgrade', :as => :checkout_update_shipment_upgrade
  post '/checkout/summary', :to => 'checkout#summary', :as => :checkout_summary
  get '/customs/bloked_user', :to => 'customs#bloked_user', :as => :customs_bloked_user
  get '/customs/blocked_guest', :to => 'customs#blocked_guest', :as => :customs_blocked_guest
  post '/admin/orders/update_shipment_upgrade', :to => 'admin/orders#update_shipment_upgrade', :as => :checkout_update_shipment_upgrade_admin
end

ammolist-master/app/views/spree/admin/shared/_additional_product_tabs.html.erb
<%= content_tag :li, :class => ('active' if current == t(:questions_and_answers)) do %>
  <%= link_to_with_icon 'tasks', t(:questions_and_answers), admin_product_questions_path(@product) %>
<% end %>

ammolist-master/app/views/spree/admin/shared/_tabs.html.erb
<% if can? :admin, Spree::Order %>
  <%= tab *Spree::BackendConfiguration::ORDER_TABS, icon: 'shopping-cart' %>
<% end %>

<% if can? :admin, Spree::Product %>
  <%= tab *Spree::BackendConfiguration::PRODUCT_TABS, icon: 'th-large' %>
<% end %>

<% if can? :admin, Spree::Admin::ReportsController %>
  <%= tab *Spree::BackendConfiguration::REPORT_TABS, icon: 'file'  %>
<% end %>

<%= tab *Spree::BackendConfiguration::CONFIGURATION_TABS, label: 'configuration', icon: 'wrench', url: spree.edit_admin_general_settings_path %>

<% if can? :admin, Spree::Promotion %>
  <%= tab *Spree::BackendConfiguration::PROMOTION_TABS, url: spree.admin_promotions_path, icon: 'bullhorn' %>
<% end %>

<% if Spree.user_class && can?(:admin, Spree.user_class) %>
  <%= tab *Spree::BackendConfiguration::USER_TABS, url: spree.admin_users_path, icon: 'user' %>
<% end %>

<% if can? :admin, Comfy::Admin::Cms %>
	<%= tab *[:blog], url: ComfortableMexicanSofa.config.admin_route_path, icon: 'file' %>
<% end %>