ammolist-master/config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :ammolist_taxon_calibers
  resources :guest_user_ips, only: [:index, :destroy] do
    collection do
      post 'block_guest'
    end
  end
  
  mount Spree::Core::Engine, :at => '/'

  get 'taxons/all_products', to: 'spree/taxons#all_products', as: :taxon_all_products
  get 'taxons/taxons_products', to: 'spree/taxons#taxons_products', as: :taxons_products
  get 'taxons/taxon_product_info', to: 'spree/taxons#taxon_product_info', as: :taxon_product_info
  get 'taxons/taxon_update_point', to: 'spree/taxons#taxon_update_point', as: :taxon_update_point
  get 'taxons/taxon_update_user_ammolist', to: 'spree/taxons#taxon_update_user_ammolist', as: :taxon_update_user_ammolist
  get 'taxons/taxon_subscribe_user_ammolist', to: 'spree/taxons#taxon_subscribe_user_ammolist', as: :taxon_subscribe_user_ammolist
  get 'taxons/taxon_get_user_ammolist', to: 'spree/taxons#taxon_get_user_ammolist', as: :taxon_get_user_ammolist
  get 'subscriptions/subscribe', to: 'spree/subscriptions#subscribe', as: :email_subscribe

  comfy_route :cms_admin, :path => ComfortableMexicanSofa.config.admin_route_path

  scope :module => :comfy, :as => :comfy do
    scope :module => :admin do
      namespace :cms, :as => :admin_cms, :path => 'admin', :except => :show do
        scope :path => ComfortableMexicanSofa.config.cms_route_path do
          resources :sites do
            resources :shared_media
          end
        end
      end
    end

    scope :module => :cms do
      scope :path => ComfortableMexicanSofa.config.cms_route_path do
        get 'feed' => 'content#feed', :as => 'feed'
      end
    end
  end

  comfy_route :cms, :path => ComfortableMexicanSofa.config.cms_route_path, :sitemap => false
  
end

Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :shipping_constraints
    resources :constraint_types
    resources :ammunitions
    
    resources :products do
      resources :questions
    end
    
    resources :questions, only: [] do
      collection do
        get :pending
      end
    end
    
  end
  
  resources :questions, only: [:create]
  
  post '/checkout/update_delivery', :to => 'checkout#update_delivery', :as => :checkout_update_delivery
  post '/checkout/update_shipment_upgrade', :to => 'checkout#update_shipment_upgrade', :as => :checkout_update_shipment_upgrade
  post '/checkout/summary', :to => 'checkout#summary', :as => :checkout_summary
  get '/customs/bloked_user', :to => 'customs#bloked_user', :as => :customs_bloked_user
  get '/customs/blocked_guest', :to => 'customs#blocked_guest', :as => :customs_blocked_guest
  post '/admin/orders/update_shipment_upgrade', :to => 'admin/orders#update_shipment_upgrade', :as => :checkout_update_shipment_upgrade_admin
end

ammolist-master/app/models/comfy/cms/page.rb
# encoding: utf-8

class Comfy::Cms::Page < ActiveRecord::Base
  self.table_name = 'comfy_cms_pages'

  cms_acts_as_tree :counter_cache => :children_count
  cms_is_categorized
  cms_is_mirrored
  cms_manageable
  cms_has_revisions_for :blocks_attributes

  # -- Relationships --------------------------------------------------------
  belongs_to :site
  belongs_to :layout
  belongs_to :target_page,
    :class_name => 'Comfy::Cms::Page'

  # -- Callbacks ------------------------------------------------------------
  before_validation :assigns_label,
                    :assign_parent,
                    :escape_slug,
                    :assign_full_path
  before_create     :assign_position
  after_save        :sync_child_full_paths!
  after_find        :unescape_slug_and_path

  # -- Validations ----------------------------------------------------------
  validates :site_id,
    :presence   => true
  validates :label,
    :presence   => true
  validates :slug,
    :presence   => true,
    :uniqueness => { :scope => :parent_id },
    :unless     => lambda{ |p| p.site && (p.site.pages.count == 0 || p.site.pages.root == self) }
  validates :layout,
    :presence   => true
  validate :validate_target_page
  validate :validate_format_of_unescaped_slug

  # -- Scopes ---------------------------------------------------------------
  default_scope -> { order('comfy_cms_pages.position') }
  scope :published, -> { where(:is_published => true) }
  scope :shared, -> { where(:is_shared => true) }

  # -- Class Methods --------------------------------------------------------
  # Tree-like structure for pages
  def self.options_for_select(site, page = nil, current_page = nil, depth = 0, exclude_self = true, spacer = '. . ')
    return [] if (current_page ||= site.pages.root) == page && exclude_self || !current_page
    out = []
    out << [ "#{spacer*depth}#{current_page.label}", current_page.id ] unless current_page == page
    current_page.children.each do |child|
      out += options_for_select(site, page, child, depth + 1, exclude_self, spacer)
    end if current_page.children_count.nonzero?
    return out.compact
  end

  # -- Instance Methods -----------------------------------------------------
  # For previewing purposes sometimes we need to have full_path set. This
  # full path take care of the pages and its childs but not of the site path
  def full_path
    self.read_attribute(:full_path) || self.assign_full_path
  end

  # Somewhat unique method of identifying a page that is not a full_path
  def identifier
    self.parent_id.blank?? 'index' : self.full_path[1..-1].slugify
  end

  # Full url for a page
  def url(relative = false)
    public_cms_path = ComfortableMexicanSofa.config.public_cms_path || '/'
    if relative
      [public_cms_path, self.site.path, self.full_path].join('/').squeeze('/')
    else
      '//' + [self.site.hostname, public_cms_path, self.site.path, self.full_path].join('/').squeeze('/')
    end
  end

  # Get Page content from block
  def block_content
    content = ''
    @block = Comfy::Cms::Block.where(identifier: "content", blockable_id: self.id, blockable_type: "Comfy::Cms::Page").first
    if @block
      content = @block.content
    end
    content
  end

protected

  def assigns_label
    self.label = self.label.blank?? self.slug.try(:titleize) : self.label
  end

  def assign_parent
    return unless site
    self.parent ||= site.pages.root unless self == site.pages.root || site.pages.count == 0
  end

  def assign_full_path
    self.full_path = self.parent ?
      [CGI::escape(self.parent.full_path).gsub('%2F', '/'), self.slug].join('/').squeeze('/') :
      '/'
  end

  def assign_position
    return unless self.parent
    return if self.position.to_i > 0
    max = self.parent.children.maximum(:position)
    self.position = max ? max + 1 : 0
  end

  def validate_target_page
    return unless self.target_page
    p = self
    while p.target_page do
      return self.errors.add(:target_page_id, 'Invalid Redirect') if (p = p.target_page) == self
    end
  end

  def validate_format_of_unescaped_slug
    return unless slug.present?
    unescaped_slug = CGI::unescape(self.slug)
    errors.add(:slug, :invalid) unless unescaped_slug =~ /^\p{Alnum}[\.\p{Alnum}\p{Mark}_-]*$/i
  end

  # Forcing re-saves for child pages so they can update full_paths
  def sync_child_full_paths!
    return unless full_path_changed?
    children.each do |p|
      p.update_column(:full_path, p.send(:assign_full_path))
      p.send(:sync_child_full_paths!)
    end
  end

  # Escape slug unless it's nonexistent (root)
  def escape_slug
    self.slug = CGI::escape(self.slug) unless self.slug.nil?
  end

  # Unescape the slug and full path back into their original forms unless they're nonexistent
  def unescape_slug_and_path
    self.slug       = CGI::unescape(self.slug)      unless self.slug.nil?
    self.full_path  = CGI::unescape(self.full_path) unless self.full_path.nil?
  end

end

ammolist-master/app/models/comfy/cms/pages_share.rb
class ComfyCmsPagesShare < ActiveRecord::Base
end

ammolist-master/app/models/comfy/cms/shared_media.rb
class Comfy::Cms::SharedMedia < ActiveRecord::Base
  self.table_name = 'comfy_cms_shared_media'

  # -- Relationships --------------------------------------------------------
  belongs_to :site
  with_options :dependent => :destroy do |shared_media|
    shared_media.has_many :shared_media_keys, class_name: "Comfy::Cms::SharedMediaKey"
  end

  accepts_nested_attributes_for :shared_media_keys
end

ammolist-master/app/models/comfy/cms/shared_media_key.rb
class Comfy::Cms::SharedMediaKey < ActiveRecord::Base
  self.table_name = 'comfy_cms_shared_media_keys' 
  # -- Relationships --------------------------------------------------------
  belongs_to :shared_media, class_name: "Comfy::Cms::SharedMedia"
end

ammolist-master/app/controllers/comfy/admin/cms/pages_controller.rb
class Comfy::Admin::Cms::PagesController < Comfy::Admin::Cms::BaseController

  before_action :check_for_layouts, :only => [:new, :edit]
  before_action :build_cms_page,    :only => [:new, :create]
  before_action :load_cms_page,     :only => [:edit, :update, :destroy]
  before_action :authorize
  before_action :preview_cms_page,  :only => [:create, :update]

  def index
    return redirect_to :action => :new if site_has_no_pages?

    @pages_by_parent = pages_grouped_by_parent

    if params[:category].present?
      @pages = @site.pages.includes(:categories).for_category(params[:category]).order('label')
    else
      @pages = [@site.pages.root].compact
    end
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @page.save!
    post_to_media if params[:page][:is_shared].to_s == "1"
    flash[:success] = I18n.t('comfy.admin.cms.pages.created')
    redirect_to :action => :edit, :id => @page
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = I18n.t('comfy.admin.cms.pages.creation_failure')
    render :action => :new
  end

  def update
    @page.save!
    post_to_media if params[:page][:is_shared].to_s == "1"
    flash[:success] = I18n.t('comfy.admin.cms.pages.updated')
    redirect_to :action => :edit, :id => @page
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = I18n.t('comfy.admin.cms.pages.update_failure')
    render :action => :edit
  end

  def destroy
    @page.destroy
    flash[:success] = I18n.t('comfy.admin.cms.pages.deleted')
    redirect_to :action => :index
  end

  def form_blocks
    @page = @site.pages.find_by_id(params[:id]) || @site.pages.new
    @page.layout = @site.layouts.find_by_id(params[:layout_id])
  end

  def toggle_branch
    @pages_by_parent = pages_grouped_by_parent
    @page = @site.pages.find(params[:id])
    s   = (session[:cms_page_tree] ||= [])
    id  = @page.id.to_s
    s.member?(id) ? s.delete(id) : s << id
  rescue ActiveRecord::RecordNotFound
    # do nothing
  end

  def reorder
    (params[:comfy_cms_page] || []).each_with_index do |id, index|
      ::Comfy::Cms::Page.where(:id => id).update_all(:position => index)
    end
    render :nothing => true
  end

protected

  def site_has_no_pages?
    @site.pages.count == 0
  end

  def pages_grouped_by_parent
    @site.pages.includes(:categories).group_by(&:parent_id)
  end

  def check_for_layouts
    if @site.layouts.count == 0
      flash[:danger] = I18n.t('comfy.admin.cms.pages.layout_not_found')
      redirect_to new_comfy_admin_cms_site_layout_path(@site)
    end
  end

  def build_cms_page
    @page = @site.pages.new(page_params)
    @page.parent ||= (@site.pages.find_by_id(params[:parent_id]) || @site.pages.root)
    @page.layout ||= (@page.parent && @page.parent.layout || @site.layouts.first)
  end

  def load_cms_page
    @page = @site.pages.find(params[:id])
    @page.attributes = page_params
    @page.layout ||= (@page.parent && @page.parent.layout || @site.layouts.first)
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = I18n.t('comfy.admin.cms.pages.not_found')
    redirect_to :action => :index
  end

  def preview_cms_page
    if params[:preview]
      layout = @page.layout.app_layout.blank?? false : @page.layout.app_layout
      @cms_site   = @page.site
      @cms_layout = @page.layout
      @cms_page   = @page

      # Chrome chokes on content with iframes. Issue #434
      response.headers['X-XSS-Protection'] = '0'

      render :inline => @page.render, :layout => layout, :content_type => 'text/html'
    end
  end

  def post_to_media
    # facebook
    @fb = @site.shared_media.find_by_name("Facebook")
    if (@fb)
      connection = @fb.shared_media_keys.first
      time1 = Time.new
      if connection
        @api = Koala::Facebook::API.new(connection.value)
        @api.put_wall_post("#{@page.label} #{@page.url} #{time1.to_s}")
      end
    end

    # twitter
    @twitter = @site.shared_media.find_by_name("Twitter")
    if (@twitter)
      connection = @twitter.shared_media_keys.find_all
      if connection
        client = Twitter::REST::Client.new do |config|
          connection.each do |conn|
          case conn.name
            when "consumer_key"
              config.consumer_key = conn.value
            when "consumer_secret"
              config.consumer_secret = conn.value
            when "access_token"
              config.access_token = conn.value
            when "access_token_secret"
              config.access_token_secret = conn.value
            end
          end
        end
        client.update("#{@page.label} #{@page.url}")
      end
    end
    
    # for google_plus use dlvr.it & rss feed
    
  end

  def page_params
    params.fetch(:page, {}).permit!
  end
end

ammolist-master/app/controllers/comfy/admin/cms/shared_media_controller.rb
class Comfy::Admin::Cms::SharedMediaController < Comfy::Admin::Cms::BaseController

  before_action :build_cms_shared_media,    :only => [:new, :create]
  before_action :load_cms_shared_media,     :only => [:edit, :update, :destroy]
  before_action :authorize
  
  def index
    return redirect_to :action => :new if @site.shared_media.count == 0
    @shared_media = @site.shared_media
  end

  def new
    render
  end

  def edit
    render
  end

  def update
    @shared_media.save!
    flash[:success] = I18n.t('comfy.admin.cms.shared_media.updated')
    redirect_to :action => :edit, :id => @shared_media
  rescue ActiveRecord::RecordInvalids
    flash.now[:danger] = I18n.t('comfy.admin.cms.shared_media.update_failure')
    render :action => :edit
  end

protected

  def build_cms_shared_media
    @shared_media = @site.shared_media.new(shared_media_params)
  end

  def load_cms_shared_media
    @shared_media = @site.shared_media.find(params[:id])
    @shared_media.attributes = shared_media_params
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = I18n.t('comfy.admin.cms.shared_media.not_found')
    redirect_to :action => :index
  end

  def shared_media_params
    params.fetch(:shared_media, {}).permit!
  end
end

ammolist-master/app/controllers/comfy/cms/content_controller.rb
class Comfy::Cms::ContentController < Comfy::Cms::BaseController

  # Authentication module must have `authenticate` method
  include ComfortableMexicanSofa.config.public_auth.to_s.constantize

  before_action :load_fixtures
  before_action :load_cms_page,
                :authenticate,
                :only => :show

  rescue_from ActiveRecord::RecordNotFound, :with => :page_not_found

  def show
    if @cms_page.target_page.present?
      redirect_to @cms_page.target_page.url(:relative)
    else
      respond_to do |format|
        format.html { render_page }
        format.json { render :json => @cms_page }
      end
    end
  end

  def render_sitemap
    render
  end

  def feed
    @layout = Comfy::Cms::Layout.find_by_label('Post')
    @pages = @cms_site.pages.unscope(:order).published.shared.where(:layout_id => @layout.id).order('comfy_cms_pages.updated_at')
    render action: 'feed.rss.builder'
  end

protected

  def render_page(status = 200)
    if @cms_layout = @cms_page.layout
      app_layout = (@cms_layout.app_layout.blank? || request.xhr?) ? false : @cms_layout.app_layout
      render  :inline       => @cms_page.content_cache,
              :layout       => app_layout,
              :status       => status,
              :content_type => mime_type
    else
      render :text => I18n.t('comfy.cms.content.layout_not_found'), :status => 404
    end
  end

  # it's possible to control mimetype of a page by creating a `mime_type` field
  def mime_type
    mime_block = @cms_page.blocks.find_by_identifier(:mime_type)
    mime_block && mime_block.content || 'text/html'
  end

  def load_fixtures
    return unless ComfortableMexicanSofa.config.enable_fixtures
    ComfortableMexicanSofa::Fixture::Importer.new(@cms_site.identifier).import!
  end

  def load_cms_page
    @cms_page = @cms_site.pages.published.find_by_full_path!("/#{params[:cms_path]}")
  end

  def page_not_found
    @cms_page = @cms_site.pages.published.find_by_full_path!('/404')

    respond_to do |format|
      format.html { render_page(404) }
    end
  rescue ActiveRecord::RecordNotFound
    raise ActionController::RoutingError.new("Page Not Found at: \"#{params[:cms_path]}\"")
  end
end

ammolist-master/app/views/comfy/admin/cms/shared_media/_form.html.haml
= render 'comfy/admin/cms/partials/shared_media_form_before', :form => form

= form.text_field :name

= form.text_area :info

= form.form_group :is_active do
  = form.check_box :is_active, :label => t('is_active')

- if @shared_media.shared_media_keys.present?
  = field_set_tag t('.access_properties') do
    = form.fields_for :shared_media_keys do |smk|
      = smk.text_field :name
      = smk.text_area :value
      %br/

= render 'comfy/admin/cms/partials/shared_media_form_after', :form => form

= form.form_group :class => 'form-actions' do
  = form.submit t(@shared_media.new_record?? '.create' : '.update'), :class => 'btn btn-primary'
  = link_to t('.cancel'), comfy_admin_cms_site_shared_media_path, :class => 'btn btn-link'

ammolist-master/app/views/comfy/admin/cms/shared_media/_form_blocks.html.haml
- namespace = { }
- cms_object = @page || cms_object
- tags = cms_object.tags(true).select{|t| t.is_cms_block?}.uniq{|t| t.identifier}
- tags.each do |tag|
  - namespace[tag.namespace || 'default'] ||= []
  - namespace[tag.namespace || 'default'] << tag

#form-blocks
  - if tags.empty?
    .no-tags
      = link_to cms_object.layout.label, edit_comfy_admin_cms_site_layout_path(@site, cms_object.layout)
      = t('.no_tags').html_safe

  - else
    = fields_for :blocks, nil, :builder => ComfortableMexicanSofa::FormBuilder, :layout => :horizontal do |cms_blocks|

      .tabbable
        - if namespace.size > 1
          %ul.nav.nav-tabs
            - namespace.each_with_index do |(name, tags), index|
              %li{:class => index == 0 ? 'active' : nil}
                = link_to name.humanize, "#ns-#{name}", :data => {:toggle => 'tab'}
        .tab-content
          - block_index = 0
          - namespace.each_with_index do |(name, tags), index|
            .tab-pane{:id => "ns-#{name}", :class => index == 0 ? 'active' : nil}
              - tags.each do |tag|
                - begin
                  = cms_blocks.send(tag.class.to_s.demodulize.underscore, tag, block_index)
                - rescue
                  - Rails.env.production?? nil : raise
                - block_index += 1

ammolist-master/app/views/comfy/admin/cms/shared_media/_index_branch.html.haml
- shared_media        ||= index_branch

%li{:id => dom_id(shared_media)}
  .item
    .toggle{:class => branch_open ? 'open' : nil}
      - if !category_view && has_children && !page.root?
        = link_to toggle_branch_comfy_admin_cms_site_page_path(@site, page), :remote => true do
          %span= t('.toggle')
        
    .icon{:class => page.is_published?? 'published' : 'draft'}
      - if !category_view && has_siblings
        .dragger
          %span &#8645;
          
    .btn-group.btn-group-sm
      = link_to t('.add_child_page'), new_comfy_admin_cms_site_page_path(@site, :parent_id => page.id), :class => 'btn btn-default'
      = link_to t('.edit'), edit_comfy_admin_cms_site_page_path(@site, page), :class => 'btn btn-default'
      = link_to t('.delete'), comfy_admin_cms_site_page_path(@site, page), :method => :delete, :data => {:confirm => t('.are_you_sure')}, :class => 'btn btn-danger'
      
    .item-content
      .item-title
        = link_to page.label, edit_comfy_admin_cms_site_page_path(@site, page), :class => 'item-label'
        = render :partial => 'comfy/admin/cms/categories/categories', :object => page
      .item-meta
        = link_to page.url, page.url, :target => '_blank'
        
  - if !category_view && has_children && branch_open
    %ul.children.sortable
      = render :partial => 'index_branch', :collection => children

ammolist-master/app/views/comfy/admin/cms/shared_media/edit.html.haml
.shared_media-header
  %h2= t('.title')

- content_for :right_column do
  = render 'comfy/admin/cms/sites/mirrors', :object => @shared_media

= comfy_form_for @shared_media, :as => :shared_media, :url => {:action => :update}, :html => {:multipart => true} do |form|
  = render form

ammolist-master/app/views/comfy/admin/cms/shared_media/form_blocks.js.erb
$('#form-blocks').replaceWith('<%= escape_javascript(render(:partial => "form_blocks")) %>');

ammolist-master/app/views/comfy/admin/cms/shared_media/index.html.haml
.page-header
  %h2= t('.title')

- content_for :right_column do
  = render 'comfy/admin/cms/sites/mirrors'

= render 'comfy/admin/cms/partials/shared_media_before'

%table.table.table-hover.table-bordered
  %tbody.sortable
    - @shared_media.each do |shared_media|
      %tr{:id => dom_id(shared_media)}
        %td
          .icon
            - if @site.shared_media.count > 1
              .dragger
                %span &#8645;
        %td.main
          .item-title
            = link_to shared_media.name, edit_comfy_admin_cms_site_shared_medium_path(@site, shared_media)
          .item-meta
            = shared_media.name
        %td
          .btn-group.btn-group-sm
            = link_to t('.edit'), edit_comfy_admin_cms_site_shared_medium_path(@site, shared_media), :class => 'btn btn-default'

= render 'comfy/admin/cms/partials/shared_media_after'

ammolist-master/app/views/comfy/admin/cms/shared_media/new.html.haml
.page-header
  %h2= t('.title')

= comfy_form_for @page, :as => :page, :url => {:action => :create}, :html => {:multipart => true} do |form|
  = render form

ammolist-master/app/views/comfy/admin/cms/shared_media/toggle_branch.js.erb
var li = $('li#comfy_cms_page_<%=@page.id%>');
li.find('.item .toggle').first().toggleClass('open');

<% if session[:cms_page_tree].member?(@page.id.to_s) %>
  if(!li.find('ul.children')[0]) {
    li.append('<ul class="children sortable"><%= escape_javascript(render :partial => "index_branch", :collection => @page.children) %></ul>');
    CMS.sortable_list();
  }
<% else %>
  li.find('ul.children').remove();
<% end %>